### ISSUE TITLE
revise the inputs and output of MLD

### ISSUE THREAD

**Issue by cshjin** [cshjin/swmp_ml#19]
Input: part of the buses are perturbed in pd and qd
* [x] replace the pertueb pd/qd 
```
# TODO: replace the net_data['load'] with buses in mods file
for k in net_data['load']:
    # update pd/qd with augmented config
    mpc['bus'].loc[mpc['bus']['bus_i'] == int(k), "Pd"] = net_data['load'][k]['pd'] * 100
    mpc['bus'].loc[mpc['bus']['bus_i'] == int(k), "Qd"] = net_data['load'][k]['qd'] * 100
```

output: 
  * [x] reg - only consider the buses (load) with active status
    * [x] replace `y = [res_data['solution']['load'][k]['qd'] for k in sorted(res_data['solution']['load'].keys())]` with keys in mods only
    * [x] update the output from `forward` function with aligned keys only 
  * [x] clf - all buses
